
// app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import './globals.css'; // Import glnobal styles
import Navbar from "./component/nav"

// Font setup
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="font-geist-sans">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
